name: ptrack_data
description: "Data layer for ptrack."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.28.1
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  ptrack_domain:
    path: ../ptrack_domain
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.32

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.28.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
